Suviseth/urls.py
from django.contrib import admin
from django.urls import path,include
from SuvisethApp import views
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('termsAndConditions/',views.termsAndCondition,name='termsAndConditions'),
    path('privacyAndPolicy/',views.privacyAndPolicy,name='privacyAndPolicy'),
    path('',include('SuvisethApp.urls'))
]

SuvisethApp/urls.py
import django
from django.conf.urls import url
from django.urls import path
from django.http import request
from SuvisethApp import views
from django.conf import settings
from django.conf.urls.static import static

#TEMPLATE TAGGING
app_name = 'SuvisethApp'

urlpatterns = [
    path('signup',views.signUp,name='signup'),
    path('signin',views.signIn,name='signin'),
    path('client_signup',views.clientSignup,name='client_signup'),
    path('sprovider_signup',views.sproviderSignup,name='sprovider_signup'),
    path('admin_signup',views.adminSignup,name='admin_signup'),
    path('client_signin',views.clientSignin,name='client_signin'),
    path('sprovider_signin',views.sproviderSignin,name='sprovider_signin'),
    path('admin_signin',views.adminSignin,name='admin_signin'),
    path('signout',views.user_logout,name='signout'),
    path('wedding_services',views.weddingServices,name='wedding_services'),
    path('find_partner',views.findPartner,name='find_partner'),

    path('categories',views.categories,name='categories'),
    path('category/<str:category_id>',views.category,name='category'),
    path('add_category',views.add_category,name='add_category'),
    path('edit_category/<str:category_id>',views.edit_category,name='edit_category'),
    path('delete_category/<str:category_id>',views.delete_category,name='delete_category'),

    path('all_service_providers',views.service_providers,name='all_service_providers'),
    path('all_service_provider/<str:sp_id>',views.service_provider,name='service_provider'),
    path('edit_service_provider/<str:sp_id>',views.edit_service_provider,name='edit_service_provider'),
    path('delete_service_provider/<str:sp_id>',views.delete_service_provider,name='delete_service_provider'),

    path('all_customers',views.customers,name='customers'),
    path('customer/<str:c_id>',views.customer,name='customer'),
    path('deactivate_account/<str:c_id>',views.remove_customer,name='remove_customer'),


] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SuvisethApp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.db import models
from django.forms import fields, formsets, widgets
from django.forms.forms import Form
from SuvisethApp.models import Admin, Category, ServiceProvider, Customer

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}),
            'email': forms.EmailInput(attrs={'class':'form-control','placeholder':'Email Id'}),
            'password': forms.PasswordInput(attrs={'class':'form-control','placeholder':'Email Id'}),
        }

class ClientForm(forms.ModelForm):
    class Meta():
        model = Customer
        fields = ('profile_pic','first_name','last_name','date_of_birth','mobile_no','address','district')

        widgets = {
            'profile_pic': forms.FileInput(attrs={'class':'form-control'}),
            'first_name': forms.TextInput(attrs={'class':'form-control','placeholder':'First Name'}),
            'last_name': forms.TextInput(attrs={'class':'form-control','placeholder':'Last Name'}),
            'date_of_birth': forms.DateInput(attrs={'class':'form-control','placeholder':'MM/DD/YYYY'}),
            'mobile_no': forms.TextInput(attrs={'class':'form-control','placeholder':'07xxxxxxxx'}),
            'address': forms.Textarea(attrs={'class':'form-control'}),
            'district': forms.Select(attrs={'class':'form-control'})
        }
        
        

class ServiceProviderForm(forms.ModelForm):
    class Meta():
        model = ServiceProvider
        fields = ('company_logo','company_name','mobile_no','district')

        widgets = {
            'company_logo': forms.FileInput(attrs={'class':'form-control'}),
            'company_name': forms.TextInput(attrs={'class':'form-control','placeholder':'First Name'}),
            'mobile_no': forms.TextInput(attrs={'class':'form-control','placeholder':'07xxxxxxxx'}),
            'district': forms.Select(attrs={'class':'form-control'})
        }

class AdminForm(forms.ModelForm):
    class Meta():
        model = Admin
        fields = ('profile_pic',)

        widgets = {
            'profile_pic': forms.FileInput(attrs={'class':'form-control'}),
        }

class CategoryForm(forms.ModelForm):
    class Meta():
        model = Category
        fields = ('name','description','images')
    
    widgets = {
        'name': forms.TextInput(attrs={'class':'form-control','placeholder':'Service Name'}),
        'description': forms.Textarea(attrs={'class':'form-control'}),
        'images': forms.FileInput(attrs={'class':'form-control'}),
    }
        

    

SuvisethApp/views.py
from SuvisethApp.models import Category, Customer, ServiceProvider
from SuvisethApp.forms import AdminForm, CategoryForm, ClientForm, ServiceProviderForm, UserForm
from django.shortcuts import redirect, render
from django.views.generic import View

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# # Create your views here.

def termsAndCondition(request):
    return render(request,'SuvisethApp/termsAndConditions.html')

def privacyAndPolicy(request):
     return render(request,'SuvisethApp/privacyAndPolicy.html')

def index(request):
    return render(request,'SuvisethApp/index.html')

def weddingServices(request):
    return render(request,'SuvisethApp/wedding_services.html')

@login_required
def findPartner(request):
    return render(request,'SuvisethApp/find_partner.html')

def signUp(request):
    return render(request,'SuvisethApp/registration.html')

def signIn(request):
    return render(request,'SuvisethApp/signin.html')

def clientSignup(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        client_form = ClientForm(data=request.POST)

        if user_form.is_valid() and client_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            client = client_form.save(commit=False)
            client.user = user

            if 'profile_pic' in request.FILES:
                client.profile_pic = request.FILES['profile_pic']

            client.save()

            registered = True

        else:
            print(user_form.errors,client_form.errors)
    
    else:
        user_form = UserForm()
        client_form = ClientForm()

    return render(request,'SuvisethApp/client_signup.html',
                     {'user_form':user_form,
                    'client_form':client_form,
                    'registered':registered})

def sproviderSignup(request):
     
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        sprovider_form = ServiceProviderForm(data=request.POST)

        if user_form.is_valid() and sprovider_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            sprovider = sprovider_form.save(commit=False)
            sprovider.user = user

            if 'company_logo' in request.FILES:
                sprovider.company_logo = request.FILES['company_logo']

            sprovider.save()

            registered = True

        else:
            print(user_form.errors,sprovider_form.errors)
            print(user_form.errors,sprovider_form.errors)
    
    else:
        user_form = UserForm()
        sprovider_form = ServiceProviderForm()
    return render(request,'SuvisethApp/sprovider_signup.html',
                            {'user_form':user_form,
                        'sprovider_form':sprovider_form,
                        'registered':registered}) 

def adminSignup(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        admin_form = AdminForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            admin = admin_form.save(commit=False)
            admin.user = user

            if 'profile_pic' in request.FILES:
                admin.profile_pic = request.FILES['profile_pic']

            admin.save()

            registered = True
        else:
            print(user_form.errors,admin_form.errors)
    else:
        user_form = UserForm()
        admin_form = AdminForm()

    return render(request,'SuvisethApp/admin_signup.html',
                            {'user_form':user_form,
                            'admin_form':admin_form,
                            'registered':registered}) 

def clientSignin(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('SuvisethApp:wedding_services'))
            else: 
                return redirect("Account not active")
        else:
            print('Some one is tried and failed')
            print("username : {} and password {}".format(username,password))
            return HttpResponse("Invalid login details supplied!")
    else:
        return render(request,'SuvisethApp/client_signin.html')



def sproviderSignin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('SuvisethApp:wedding_services'))
            else: 
                return redirect("Account not active")
        else:
            print('Some one is tried and failed')
            print("username : {} and password {}".format(username,password))
            return HttpResponse("Invalid login details supplied!")
    else:
        return render(request,'SuvisethApp/sprovider_signin.html')

def adminSignin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('SuvisethApp:wedding_services'))
            else: 
                return redirect("Account not active")
        else:
            print('Some one is tried and failed')
            print("username : {} and password {}".format(username,password))
            return HttpResponse("Invalid login details supplied!")
    else:
        return render(request,'SuvisethApp/admin_signin.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('SuvisethApp:signin'))

@login_required
def categories(request):
    services = Category.objects.all()
    return render(request,'SuvisethApp/category/categories.html',
                            {'services':services})

@login_required
def add_category(request):
    if request.method == "POST":
        category_form = CategoryForm(request.POST)

        if category_form.is_valid:
            category = category_form.save()
            

            if 'images' in request.FILES:
                category.images = request.FILES['images']
                category.save()
                return HttpResponseRedirect(reverse('SuvisethApp:categories'))
        
        else:
            print(category_form.errors)

    else:
        category_form = CategoryForm()

    return render(request,'SuvisethApp/category/add_category.html',
                        {'category_form':category_form})

@login_required
def edit_category(request,category_id):
    category = Category.objects.get(id=category_id)
    category_form = CategoryForm(instance=category)

    if request.method == "POST":
        category_form = CategoryForm(request.POST,instance=category)

        if category_form.is_valid:
            category = category_form.save()
            
            if 'images' in request.FILES:
                category.images = request.FILES['images']
                category.save()
                return HttpResponseRedirect(reverse('SuvisethApp:categories'))
        
        else:
            print(category_form.errors)

    return render(request,'SuvisethApp/category/edit_category.html',
                            {'category_form':category_form})

@login_required
def delete_category(request,category_id):
    category = Category.objects.get(id=category_id)
    if request.method == 'POST':
        category.delete()
        return redirect('/categories')
    return render(request, 'SuvisethApp/category/delete_category.html',
                            {'category':category})

@login_required
def category(request,category_id):
    category = Category.objects.get(id=category_id)
    return render(request, 'SuvisethApp/category/category.html',
                            {'category':category})

@login_required
def service_providers(request):
    service_providers = ServiceProvider.objects.all()
    return render(request, 'SuvisethApp/admin_service_providers/all_service_providers.html',
                            {'service_providers':service_providers})

@login_required
def service_provider(request,sp_id):
    service_provider = ServiceProvider.objects.get(id=sp_id)
    return render(request, 'SuvisethApp/admin_service_providers/service_provider.html',
                            {'service_provider':service_provider})

@login_required
def edit_service_provider(request,sp_id):
    service_provider = ServiceProvider.objects.get(id=sp_id)
    s_provider_form = ServiceProviderForm(instance=service_provider)

    if request.method == "POST":
        s_provider_form = ServiceProviderForm(request.POST,instance=service_provider)

        if s_provider_form.is_valid:
            service_provider = s_provider_form.save()
            
            if 'company_logo' in request.FILES:
                service_provider.company_logo = request.FILES['company_logo']
                service_provider.save()
                return HttpResponseRedirect(reverse('SuvisethApp:all_service_providers'))
        
        else:
            print(s_provider_form.errors)

templates/SuvisethApp/admin_signin.html
<!DOCTYPE html>

<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="Kavinda Perera">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="/static/css/login.css">

  <title>Login</title>

</head>

<body style="min-height: 100vh;
            margin-top: 50px;">

  <!-- login section -->
  <section class="login-block">
    <div class="container">
      <div class="row">
        <div class="col-md-4 login-sec">
          <h2 class="text-center">Login Now</h2>

          <!-- login form -->
          <form class="login-form" method="POST">
            {% csrf_token %}
            <div class="form-group my-2">
              <label for="exampleInputEmail1" class="text-uppercase">Username</label>
              <input name="username" type="text" class="form-control" placeholder="" required>
            </div>
            <div class="form-group my-2">
              <label for="exampleInputPassword1" class="text-uppercase">Password</label>
              <input name="password" type="password" class="form-control" placeholder="" required>
            </div>
            <div class="form-check">
              <label class="form-check-label my-2">
                <input type="checkbox" class="form-check-input" required="required">
                <small  class="text-white">Check here to indicate that you have read and agree to the <a class="text-white" href="{% url 'termsAndConditions' %}">Terms Agreement</a> and the <a  class="text-white" href="{% url 'privacyAndPolicy' %}">Privacy Policy Agreement</a>  of the Suviseth"</small>
              </label>
            </div>
          <div>
              <button type="submit" class="btn btn-login float-right my-2 col-md-12 rounded-pill">Submit</button>
            </div>

          </form>
          <!-- end of login form -->

        </div>
        <div class="col-md-8 banner-sec">
          <!-- carousel -->
          <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">

            <!-- carousel indicator -->
            <div class="carousel-indicators">
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
            </div>
            <!-- end of carousel indicator -->

            <!-- carousel-inner -->
            <div class="carousel-inner">

              <!-- first carousel-item -->
              <div class="carousel-item active">
                <img src="/static/images/logos/color_logo_transparent.png" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                  <p class="h1 text-dark">Slide 1</p>
                  <p class="text-dark">Some representative placeholder content for the first slide.</p>
                </div>
              </div>
              <!-- end of first carousel item -->

              <!-- second carousel-item -->
              <div class="carousel-item">
                <img src="/static/images/logos/suviseth_color_logo-original.png" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                  <p class="h1 text-dark">Slide 2</p>
                  <p class="text-dark">Some representative placeholder content for the second slide.</p>
                </div>
              </div>
              <!-- end of second carousel item -->

              <!-- third carousel item -->
              <div class="carousel-item">
                <img src="/static/images/logos/dark_logo_transparent.png" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                  <p class="h1 text-dark">Slide 3</p>
                  <p class="text-dark">Some representative placeholder content for the third slide.</p>
                </div>
              </div>
              <!-- end of third carousel item -->

            </div>
            <!-- end of carousel inner -->
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
              data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
              data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
          <!-- end of carousel -->

        </div>
      </div>
    </div>
  </section>
  <!-- end of login section -->


  <!--Separate Popper and Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>

</body>

</html>

templates/SuvisethApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
 
		<!-- STYLE CSS -->
		
    <link rel="stylesheet" href="/static/css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/> -->
  </head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container-fluid">
            <div class="navbar-header">
                <a href="{% url 'index' %}" class="navbar-brand">Suviseth</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    {% if not user.serviceprovider and not user.admin%}
                    <li class="nav-item"><a class="nav-link active" href="{% url 'SuvisethApp:wedding_services' %}">Wedding Sevices</a></li>
                    {% endif %}
                    {% if user.is_authenticated and user.customer %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'SuvisethApp:find_partner' %}">Find Your Partner</a></li>
                    {% endif %}
                    {% if user.serviceprovider %}
                    <li class="nav-item"><a class="nav-link" href="#">My Services</a></li>
                    {% endif %}
                    {% if user.admin %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'SuvisethApp:categories' %}">Categories</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'SuvisethApp:all_service_providers' %}">Service Providers</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'SuvisethApp:customers' %}">Customers</a></li>
                    {% endif %}
                </ul>
            </div>

            <div class="justify-content-end">
                <!-- <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form> -->
                <ul class="nav navbar-nav">
                    {% if user.is_authenticated %}
                      <li class="nav-item"><a class="nav-link" href="{% url 'SuvisethApp:signout' %}"><i class="fas fa-sign-up-alt"></i> Sign out</a></li>
                    {% else %}
                      <li class="nav-item"><a class="nav-link" href="{% url 'SuvisethApp:signup' %}"><i class="fas fa-sign-up-alt"></i> Sign up</a></li>
                      <li class="nav-item"><a class="nav-link" href="{% url 'SuvisethApp:signin' %}"><i class="fas fa-sign-in-alt"></i> Sing in</a></li>
                    {% endif %}

                </ul> 
            </div>
          </div>
        </nav>
        <div class="container content-body">
            {% block body_block %}

            {% endblock %}
        </div>
        <!-- Footer -->
<footer class="text-center text-lg-start bg-dark text-muted">
    <!-- Section: Social media -->
    <section
      class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
    >
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->
  
      <!-- Right -->
       <div>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->
  
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>Company name
            </h6>
            <p>
              Here you can use rows and columns to organize your footer content. Lorem ipsum
              dolor sit amet, consectetur adipisicing elit.
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Products
            </h6>
            <p>
              <a href="#!" class="text-reset">Angular</a>
            </p>
            <p>
              <a href="#!" class="text-reset">React</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Vue</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Laravel</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="#!" class="text-reset">Pricing</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Settings</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Orders</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Help</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Contact
            </h6>
            <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              info@example.com
            </p>
            <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2021 Copyright:
      <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

templates/SuvisethApp/find_partner.html
{% extends "SuvisethApp/base.html" %}
{% block body_block %}
<div>
    <h1>Find your partner</h1>
</div>

{% endblock %}

templates/SuvisethApp/index.html
{% extends "SuvisethApp/base.html" %}
{% block body_block %}
<div>
    <h1>Welcome to Index page</h1>
</div>

{% endblock %}

templates/SuvisethApp/registration.html
{% extends "SuvisethApp/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <p><a href="{% url 'SuvisethApp:client_signup' %}">Sign up as Client</a></p>
    <p><a href="{% url 'SuvisethApp:sprovider_signup' %}">Sign up as Service Provider</a></p>
    <p><a href="{% url 'SuvisethApp:admin_signup' %}">Sign up as Admin</a></p> 

</div>

{% endblock %}

templates/SuvisethApp/signin.html
{% extends "SuvisethApp/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <p><a href="{% url 'SuvisethApp:client_signin' %}">Sign in as Client</a></p>
    <p><a href="{% url 'SuvisethApp:sprovider_signin' %}">Sign in as Service Provider</a></p>
    <p><a href="{% url 'SuvisethApp:admin_signin' %}">Sign in as Admin</a></p>
</div>

{% endblock %}

templates/SuvisethApp/wedding_services.html
{% extends "SuvisethApp/base.html" %}
{% block body_block %}
<div>
    <h1>Welcome to Wedding Services Page</h1>
</div>

{% endblock %}